version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  simulation:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/credito_onde
